### PR TITLE
Fix reset issue on search 

### PR DESCRIPTION
**Pull request by hjaintech**
Fixes issue #11

### CODE REVIEW

**Comment by hjaintech** [comment]
@sahil9001 Fixed the issue. Please merge.

**Comment by sahil9001** [comment]
@hjaintech Seems like if you search a keyword and search another keyword after that the results mix up.

**Comment by hjaintech** [comment]
> @hjaintech Seems like if you search a keyword and search another keyword after that the results mix up.

Not able to reproduce on https://react-recipe-app-git-fork-hjaintech-master.sahilsilare.now.sh
Can you tell me the exact steps ? Also is that part of this issue ?

**Comment by sahil9001** [comment]
https://react-recipe-app-3u7f9cou5.now.sh/ This deployment is giving me errors, can I know how to fix this?

**Comment by hjaintech** [comment]
@sahil9001 
1. Can you provide details about the mix up issue that you mentioned [here](https://github.com/sahil9001/react-recipe-app/pull/12#issuecomment-537908676)

2. In order to help you out, I would need more details about [this](https://github.com/sahil9001/react-recipe-app/pull/12#issuecomment-537910019).

**Comment by hjaintech** [comment]
> https://react-recipe-app-3u7f9cou5.now.sh/ This deployment is giving me errors, can I know how to fix this?, also https://react-recipe-app-git-fork-hjaintech-master.sahilsilare.now.sh try searching 'Hello' and then 'Chole' you'll see mixed results.

@sahil9001 This is happening because you are using `label` as 'key'. However it is not unique in the data that you are getting for search text `Hello`. So either make the `label` as unique OR change the `key` to something unique like an id. 

Nonetheless, this is a new unrelated issue and should be raised separately. Also I can see that changes are deployed on https://searchrec.now.sh and working fine.

**Comment by sahil9001** [comment]
@hjaintech The changes aren't deployed, I haven't merged into `master`

**Comment by hjaintech** [comment]
@sahil9001 My bad, yes changes are not deployed on https://searchrec.now.sh yet. Anyways, whats stopping you from merging this PR ?

**Pull request merged**
